apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nifi
  name: nifi
spec:
  containers:
  - image: apache/nifi:latest
    name: nifi
    ports:
    - name: http
      containerPort: 8080
    - name: https
      containerPort: 8443
    env:
      - name: NIFI_WEB_PROXY_HOST 
        value: "192.168.64.2:31821"
      - name: NIFI_WEB_HTTPS_PORT
        value: "8443"
      - name: NIFI_WEB_HTTPS_HOST
        value: "nifi"
      - name: SINGLE_USER_CREDENTIALS_PASSWORD
        value: "adminadminadmin"
      - name: SINGLE_USER_CREDENTIALS_USERNAME
        value: "admin"
    volumeMounts:
      - name: nifi
        mountPath: /opt/nifi/nifi-current/nifi_data
    resources: {}
  volumes:
    - name: nifi
      hostPath:
        path: /Users/andrew.t.jimbo/nifi_data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
